#v1.2

on: [push] 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Codespace for testing phpBB Extension
        uses: battye/phpbb-extension-tester@main