# v1.3

on: [push] 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Codespace for testing phpBB Extension
        id: create-codespace
        uses: battye/phpbb-extension-tester@main
        with:
          source-branch: '3.3.x'
          destination-branch: 'codespace-test'
      - name: Show output
        run: |
          echo destination-branch "$DESTINATION_BRANCH"
          echo "### Your Codespace is ready to run on branch $DESTINATION_BRANCH! :rocket:" >> $GITHUB_STEP_SUMMARY
        shell: bash
        env:
          DESTINATION_BRANCH: ${{ steps.create-codespace.outputs.destination-branch }}
